version: '3.9'
services:
  rustapp:
    container_name: rustapp
    image: levan02111984/rustapp:1.0.0
    build: 
       context: .
       dockerfile: Dockerfile
       args:
          DATABASE_URL: postgres://postgres:password@db:5432/postgres
    ports:
          - '8080:8080'
    depends_on:
          - db
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
